### ISSUE TITLE
HLS  index file with subtitles listed 

### ISSUE THREAD

**Issue by lordfenixnc** [luxluth/ass-html5#38]
Would it be possible to pull ass subtitles from that directory as well     or would need to be hosted separately no matter what? 

Awesome Project  and hope it continues the progress .    im currently bulk encoding to HLS  and hosting in IPFS  so having everything pull from the HLS index file would be amazing if at all possible

**Comment by luxluth** [comment]
> Would it be possible to pull ass subtitles from that directory as well or would need to be hosted separately no matter what?

I'm afraid I don't really understand the question. Can you provide me with an example ?

> Awesome Project and hope it continues the progress

Thanks. I'm going to rewrite the ass renderer so it'll be more flexible to work with
A `0.4.0` will maybe be the first release with animations and text wrapping support.

**Comment by lordfenixnc** [comment]
In hls video format. There is a generated video folder, audio folder and
subtitle  folder.  And a index file telling the web player about what's
available.   Currently web players only support vtt subs in that folder.
 Would it be possible  to read the ass files from that same folder.
Allowing everything to be accessed from the index file.      Then
everything could be pointed at the index file.

**Comment by luxluth** [comment]
Oh, I see. 
Well, you can access the ass subtitle url, right ? So if you have the url, then you can fetch the text content of it and put it into the ASS constructor.

**Comment by lordfenixnc** [comment]
True. I just need to figure out how to script it in my player so I can have
1 player script to work with multiple pages

**Comment by luxluth** [comment]
Hope you succeed
