### ISSUE TITLE
Subtitle Bug?

### ISSUE THREAD

**Issue by RawRipper** [luxluth/ass-html5#62]
Is it normal for the subtitles to be hidden when you go into full screen mode?

![image](https://github.com/luxluth/ass-html5/assets/162888950/69e4a1a1-ab21-4a8f-9427-90d484136d0c)
![image](https://github.com/luxluth/ass-html5/assets/162888950/dca5d567-0348-4348-853c-92295c5326da)

my code:

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.jsdelivr.net/npm/ass-html5@0.4.0/dist/ass.min.js"></script>
</head>
<body>
  <video id="my-video" controls preload="auto" width="1280" height="720">
    <source src="mp4/file.mp4" type="video/mp4" />
  </video>

  <script>
    document.addEventListener('DOMContentLoaded', async () => {
      let res = await fetch('legenda/1.ass');
      let assSubs = await res.text();

      var player = document.getElementById('my-video');

      player.addEventListener('loadedmetadata', async () => {
        const ass = new ASS({
          assText: assSubs,
          video: player
        });
        await ass.init();
      });
    });
  </script>
</body>
</html>
```

**Comment by RawRipper** [comment]
Ah, I went to https://asshtml5.com/ and saw that it hasn't been added yet

**Comment by luxluth** [comment]
It's actualy the normal behavior.

> [!NOTE]
> The simple `video` tag element, on fullscreen mode, the position of the video is absoluty on top of any element.
> No other element can go on top of it.
>
> It's therefore recommanded to use a third party player rather than the native one.

**Comment by RawRipper** [comment]
I see, it would be nice to have a folder with examples of how to use it, like this site from the subtitles octopus project https://libass.github.io/JavascriptSubtitlesOctopus/mediaelement.html

**Comment by luxluth** [comment]
I added two examples https://asshtml5.com/examples

**Comment by RawRipper** [comment]
Oh good, the project is cool I'm looking forward to the future of the project, I've used subtile octopus and libjass I liked them a lot

**Comment by luxluth** [comment]
Thanks. I hope compliting it soon

**Comment by RawRipper** [comment]
That's great
